---
title: "final_paper"
author: "Chris Kardish, Marie Agosta"
date: "December 8, 2016"
output: pdf_document
---

#setwd('C:/Users/Chris/Documents/GitHub/final_paper')
#rm(list = ls())

##I. Introduction/literature review (Marie)

## Research Question and introduction 

Do tradiitonal indicators of voter turnout hold the same predictive power from one generation to the next? Do other potential indicators, such as race or gender, hold more predictive power for the Millennial generation? 
 
Traditionally, an individual's age is one of the most common predictors of differences in attitudes and behaviors, particularly when it comes to voting. Age denotes what cohort a particular person belongs to and what point of the life cycle a particular person is in: childhood, young adult, middle aged, or retiree. Generations typically refer to people born over a 15-20-year span. According to the Pew Research Center, Millennials are the generation born from 1980-1994, making them approximately 22-36 years old as of 2016.
 
In the United States, for the past 25 years, the Baby Boomer generation (1946-1964) was the defining vote in presidential and down-ballot elections. However, at 75.4 million people, Millennials now outnumber the Baby Boomers '[@fry2015year]'.
 
Millennials will play an increasingly significant role in U.S. elections as they represent an ever-greater share of eligible voters, but there are substantial differences in disposition and demographics between them and previous generations, which could well mean differences in factors that bring them to the polls. Bringing millennials to the polls has been quite a challenge, they have lower turnout rates than previous generations did at that age. Given how demographically and culturally different they are, it is important to understand what actually makes them vote. 
 
Generational shifts in attitude have been well documented '[@kohut2011generation]'. Millennials are in no rush to get married, are more supportive of larger governments, are more likely to have debt, are more accepting of gay-marriage, and are more aware of gender discrimination. Additionally, most millennials came of age during a recession '[@o2015millennials]' and identify with and engage with technology in a way that was inconceivable to past generations. These societal shifts and cultural norms will affect how they view and partake in politics. Millennials are the only generation where just as many people describe their views as liberal as they do conservative. They also have the highest number of people reported as being open to a third-party candidate and are relatively unattached to organized politics and religion '[@fry2015year]'. 

Lastly, Millennials are diverse. First, the age range in and of itself implies a diversity of experience, but more importantly, according to the U.S. Census Bureau, for every 100 millennials, 44 are a part of a minority race or ethnic group.  To put it another way, in 2000 only 8 states and Washington DC had a share of minority voters that was 30% or higher. In 2012, the number of states was 17 (plus Washington DC) '[@CensusBureau.2016]'.

## Literature review

The Downsian Model of Electoral competition broadly states that if policy space is unidimensional, and voters have single-peaked preferences over the policy dimension, then the median voter becomes pivotal in majority decision making. Downs (1957) used this result to analyze electoral competition, and demonstrated that two competing parties will converge to the policy of the preferred median voter. There are quite restrictive assumptions with this model, including that politicians are able to pre-commit to their proposed platforms. That being said, the model delivers a clear prediction about the impact of electoral competition on public policy and has become a mainstay in the field. 

The original Downsian Model did not pay much attention to who the "median voter" was, so subsequent studies built on his model by showing that the median voter and median citizen are usually not one in the same. An abundant number of theoretical models have emerged, trying to explain voter turnout, yet there is limited academic consensus on a core model. Different models have found empirical support in different contexts, suggesting that perhaps voter turnout has different causal mechanisms depending upon the country, voters, and time period '[@smets2013embarrassment]'.

When it comes to the United States, non-voters have not been randomly distributed across the country. Empirical research shows that voters and nonvoters systematically differ in their socio-economic status and demographic backgrounds. These differences allude to potential differences in needs and policy preferences '[@verba1993citizen]' '[@wolfinger1980votes]'.

A highly regarded study by Raymond Wolfinger and Steven Rosenstone (1980) '[@wolfinger1980votes]' demonstrated that in the US, turnout is fairly predictable based on a number of individual demographic variables. The variables are education, income, age, marital status, and occupation. Independent of the specific election or country examined, these results have been confirmed repeatedly by subsequent studies '[@smets2013embarrassment]'. Smets and Van Ham (2012) conducted a thorough meta-analysis on individual level turnout and also found that education, age, income, and marital status were consistently statistically significant in regards to voter turnout. It should, however, be noted that there are substantial limits in the predictive and explanatory power of even well-specified statistical models. As Matsusaka (1999) has shown, voter turnout models generally suffer from a low r-squared, meaning they explain only a limited percentage of the factors behind the phenomenon '[@matsusaka1999voter]'.   

It is important to note that other empirical works '[@cox1989closeness]' '[@leighley1992socioeconomic]' have elaborated on these findings by focusing on systemic characteristics and have found that the closeness of the election, contextual socio-economic conditions, and registration laws have an impact on who goes to the polls. In a comprehensive meta-analysis on aggregate-level studies, many of which concentrated on the US (pgs. 654-657), Geys (2006) found that population size and electoral closeness, population stability, and past turnout were consistently positively significant, whereas racial diversity was consistently negatively significant. The interplay between individual predictors and systemic predictors has yet to be fully explored.

##II. Brief discussion of the data source (Marie)

Because our model will test a variety of different independent variables, we focused on a finding reputable and publicly available survey that includes key demographics along with attitudes, dispositions, past voting history, and other factors. 

The source we settled on was the 2012 Time Series Study from American National Election Studies (ANES), a joint Stanford University and University of Michigan collaboration that is widely cited in academic literature. This study has been conducted annually since 1948. The study produced a sizable (62MB) panel survey of approximately 6,000 respondents who answered two sets of questions on two separate occasions, both before the 2012 presidential election and afterward. Most responses are conducted via face-to-face interviews, however this was the first year face-to-face interviews were supplemented by internet interviews. The set includes 1,908 variables and was conducted in English and Spanish. Because this is a nationally representative sample survey, clustering and post-stratification weights were used. 

Particpants were interviewed by professionals trained with a touch sensitive tablet computer. Most of the interview was done in a computer aided personal interview format (CAPI) meaning the computer displays the question, the interviewer reads it aloud, the respondent answers verbally and the interviewer clicks the appropriate box. Interviwers were instructed to probe if people were hesitant to answer. Some questions were asked in a computer-aided self-interview format (CASI), meaning the respodent took the computer and answered questions privately. These questions were marked as such. 

Virtually any demographic variable that appears in voter turnout literature is included, such as level of education, employment status, income, race, gender, and age. It also includes more than 60 additional sections assessing a wide range of topics, from political knowledge to social trust and opinions on salient political issues.  Lastly, it includes self-reported turnout (which was later confirmed) and choice for both the 2012 and 2008 elections, allowing us to control for past voting history as well, which has been shown to be a strong predictor of future turnout and a good control for a host of time-invariant factors '[@matsusaka1999voter]'.

Additionally, a 2013 follow-up using the same participants includes a host of additional variables covering attitudes and opinions on major political issues. But this data set would have to be merged with the 2012 original using unique participant identification numbers and because of the response rate, we would be reducing our sample size if we were to incorperate the follow-up. 

##III. Methodology and model, variables included, and any cleaning that was performed (Chris) 

The traditional indicators of voter turnout: education, income, age, and marital status, were indicative of generations that were characterized by minimal minority voice, fairly traditional gender roles, minimal economic-sectoral shifts, and a lack of reliance on technology. We postulate that the Millennials, given their diversity and the time in which they came of age, may not vote according to past predictors.

We use a logistic regression to assess the strength of various predictors on the likelihood that a given respondent voted in 2012. Thus, we use a binary dependent variable coded "1" if the respondent did vote in 2012. But because our focus is to test whether traditional factors found in voter turnout literature have less predictive power for Millennials (and in turn whether there are more neglected variables that have a strong impact specifically on Millennials), we run the same model but for different age bands. This allows us to discern differences in predictive power across age groups. We use odds ratios from exponentiated coefficients to determine the overall impact of a given predictor, and we use prediction functions to assess the model's overall goodness-of-fit. 

The variables we include in the model and our hypothesize effects include the most widely cited variables from academic literature (the so-called "traditional predictors"): education, age, income, and employment status. Looking at attitude surveys of Millennials, reporting on their habits, and existing literature, we posit some of these traditional factors will have different impacts for Millennials.

##Predictions

We predict education will have less of an impact because American Millennials are actually far more educated than their parents, essentially diluting the importance of a four-year degree as a key benchmark for civic participation and income attainment '[@patten2015millennials']. 

We predict past voting decisions will not be as strong of a predictor because the habits of Millennials are not as ingrained. 

We predict income will be less significant of a predictor because it is less a part of Millennial identity and explains less about individuals in this age group '[@taylor2010millennials]'. 

We predict that gender and race will be stronger indicators than in previous generations, particularly the interactions between them. Minority Millennials compose a large portion of the whole generation, and they have been casting votes at a high enough rate to strongly influence election turnout '[@Ramsey.2016]'.
 
Additionally, the role women play in social, political, and economic life has changed dramatically through the generations. There are more women in college, more women with degrees, and more women as the sole, or primary breadwinner of the family '[@wang2013breadwinner]'. These shifts, especially the economic ones, have affected how women vote '[@iversen2006political]'. As traditional perceptions and roles have changed, social issues have also come to the forefront.

##IV. Results (mainly, tables of coefficients, exponentiated coefficients, and discussion of
##those results) (Chris)

##V. Simulations using the model (Chris)

##VI. Limitations, including Goodness-of-fit/robustness (Marie &Chris)

There are a number of limitations with our analysis and the dataset that was used. Foremost, only using 2012 to gain insight into voting indicators diminshes external validity. Ideally, panel data would be used to gain more externally valid insights into predictors. Additionally, past voting behavior in this survey, refered to the participants voting behavior in the year of 2008. The 2008 presidential election had record turnout, specifically among millennials and specifically among African-Americans. Using 2008 as a proxy for past voting behavior needs to be looked at critically as it probably overestimates past voting behavior. 

Another limitation is the response rate which was approximately 49%, the lowest the ANES study has ever recorded. Due to this, there is an increased likelihood that non-response bias affected the estimates. There was also a fair amount of item non-response, meaning selected respondents participated but only provided partial answers to some basic questions - e.g. responding to questions about employment with "I don't know" or "refused to answer."

With any household survey, there are important issues that can affect estimates, including non-response and item non-response (mentioned above) and the potential for measurment error. Measurement error refers to error among those reporting. Self survey (internet) and self report (face-to-face interview) are always vulnerable to this. Respondents can under-report, by misunderstanding a complicated question or thinking information may be passed on to tax authorities, or over-report due to human error or social desirability. Additionally, all estimates from sample surveys are subject to sampling variability. This has implications for inference about distributional comparisons, such as trends and differences. 

Goodness of fit should also be considered...

##VII. Conclusion (Marie)

Our original predictions were that education will have less of an impact for Millennials, past voting decisions and income will not be as strong of a predictor for Millennials and that gender and race will be stronger indicators than in previous generations, particularly the interactions between them. 

We discovered that... 

This... 

The remaining variance in the model potentially speaks to contextual and systemic variables that are often not looked at in conjuction with individual level indicators. The closeness of the election, contextual socio-economic conditions, and registration laws have an impact on who goes to the polls. Registration laws could be of partiuclar importance as portions of the Voting Rights Act were recently struck down and newly (re)enforced restrictions for registering and voting disporoportionatly hurt minorities. Also, Millennials move more than past generations, and in the U.S. context this entails numerous obstacles, such as registering to vote again in the new place of residence '[@benetsky2015young]'.




BELOW ARE NOTES FROM ABOVE THAT I PLAN TO INCLUDE, JUST WANT TO WAIT UNTIL IT'S ALL TOGETHER TO DO IT. 

we believe party identification will have less of an impact, given Millennials' disdain for the mobilizing effects of party identification. 

Additionally, population size and electoral closeness, andpopulation stability also have an influence.  whereas racial diversity was consistently negatively significant. The interplay between individual predictors and systemic predictors has yet to be fully explored.

Other variables of interest include civic duty, which we believe will not have as strong of an impact owing to a greater sense of social dislocation among Millennials, which will also contribute to diminished impact of membership in traditional institutions (church, unions, etc.). Because of these factors, Millennials will have to feel an especially strong attachment to a candidate in a given election in order to vote, which is measurable using ANES, and contact from a political party will have an especially high impact '[@kitchel2015they]'.

test 


# Bibliography
