---
title: "Final Project"
author: "Chris Kardish & Marie Agosta"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#setwd('C:/Users/Chris/Documents/GitHub/final_paper')
source("cleaning_final.R")
#rm(list = ls()) 
library("flexdashboard")

```



-----------------------------------------------------------------------

# Project Basics

**In the US, do traditional indicators of individual voter turnout hold the same predictive power across generations? Are there insightful differences when it comes to the Millennial generation?** 

Traditional indicators of voter turnout: 

- income 
- age
- occupation
- education 
- Past voting decisions

**Why it matters**

Approximately **69.2 million Millenials** are of voting age and are eligible to vote, making them the largest share of eligible voters yet only 45-50% of them typically vote. Millenials are demographically much more diverse than previous generations and came of age in a very secular and technology driven world 

# Methodology 

We opted for a logit model because we want to assess if traditional indicators hold the same predictive power across generations. Our dependent variable is binary: 0 - did not vote in 2012, 1 - voted in 2012. 

Independent variables (same model across 4 generations) are: 
- education
- gender (female dummy)
- income
- race (black and hispanic dummies)
- whether respondent voted in 2008 

# Choice of Data 

- American National Election Studies 
- Face to face and internet survey, N = 4,505
- Response Rates: 
    + Face-to-face: 38 percent
    + Online: 2 percent
- Over 1,900 variables
- Conducted in English and Spanish 
- Weighted survey 


# Plots 

Row
-------------------------------------

### Coefficients

```{r echo = FALSE, results='asis', message=FALSE,}
#setwd('C:/Users/Chris/Documents/GitHub/Final_Presentation')
library(stargazer)
stargazer(M_genY, M_genX, M_boomer, M_silent, apply.coef = exp,
         t.auto=F, p.auto=F, report = "vct*", font.size = 'tiny',
          type = "html",  dep.var.labels = "Probability of voting in 2012", 
          column.labels = c("Gen Y", "Gen X", "Boomers", "Silent"),
          title = "Odds Ratios Across Four Generations")
```
    
    
Row
-------------------------------------

### Chart 2

```{r, echo=FALSE, include=FALSE, message=FALSE}
library(Zelig)
Z_genY <- zelig(vote_2012 ~ education + female + vote_2008 + black + hispanic + income, model = "logit.survey", weights=~weights, strata=~strata, data = anes_genY)
Z_boomer <- zelig(vote_2012 ~ education + female + vote_2008 + black + hispanic + income, model = "logit.survey", weights=~weights, strata=~strata, 
                  data = anes_boomer)
Z_silent <- zelig(vote_2012 ~ education + female + vote_2008 + black + hispanic + income, model = "logit.survey", weights=~weights, strata=~strata, 
                  data = anes_silent)
Z_genX <- zelig(vote_2012 ~ education + female + vote_2008 + black + hispanic + income, model = "logit.survey", weights=~weights, strata=~strata, 
                  data = anes_genX)
```
```{r, message=FALSE, echo = FALSE, fig.align='center', fig.show='hold', fig.width=4, fig.height=5}
setZ_genY_black <- setx(Z_genY, education = 1:5, black = 1, hispanic = 0, 
                        income = 3, female = 1, vote_2008 = 0)
simZ_genY_black <- sim(Z_genY, x = setZ_genY_black)
ci.plot(simZ_genY_black, ylim = 0:1, ylab = "Probability of voting", 
        main = "Black Millennial Woman")
setZ_boomer_black <- setx(Z_boomer, education = 1:5, black = 1, hispanic = 0, 
                          income = 3, female = 1, vote_2008 = 0)
simZ_boomer_black <- sim(Z_boomer, x = setZ_boomer_black)
ci.plot(simZ_boomer_black, ylim = 0:1, ylab = "Probability of voting", 
        main = "Black Baby Boomer Woman")
```


Row 
-------------------------------------

### Chart 3

```{r, message=FALSE, echo = FALSE, fig.align='center', fig.show='hold', fig.width=3.5, fig.height=5}
ci.plot(simZ_genY_black, ylim = 0:1, ylab = "Probability of voting", 
        main = "Black Millennial Woman")
setZ_silent_black <- setx(Z_silent, education = 1:5, black = 1, hispanic = 0, 
                        income = 3, female = 1, vote_2008 = 0)
simZ_silent_black <- sim(Z_silent, x = setZ_silent_black)
ci.plot(simZ_silent_black, ylim = 0:1, ylab = "Probability of voting", 
        main = "Black Silent Generation Woman")
```




